### ISSUE TITLE
Cannot compile on Kubuntu 20.04

### ISSUE THREAD

**Issue by Talon1024** [ZDoom/Raze#702]
When I try to compile Raze from the Git master branch, I get this error:

```/usr/bin/ld: /home/kevinc/Games/code/Raze/build/../source/build/src/mdsprite.cpp:495: undefined reference to `hw_animsmoothing'```

I was able to compile Raze 1.5.0 just fine, so I don't know if I'm doing anything wrong. My compiler is GCC 9.4.0.

**Comment by coelckers** [comment]
fixed in 3ca9052b7abfa640cb140cbf70d982108b58ec0f

**Comment by coelckers** [comment]
fixed in 3ca9052b7abfa640cb140cbf70d982108b58ec0f
